name: Makefile CI

on:
  push:
    tags:
      - 'v*'

jobs:
  upload-release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: download artifacts
        uses: actions/download-artifact@v2
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifact/toolchain-darwin.zip
            artifact/toolchain-linux.zip
            artifcat/toolchain-win32.zip     

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: make
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        path: toolchain-*.zip
